### PR TITLE
Deploy try

### PR DESCRIPTION
**Pull request by nejraselimovic**
#### Summary
Try to make latest changes public

#### Checklist
- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by azerimaker — APPROVED** [review]
Let's try to merge this.

**Comment by elsalahy** [comment]
@nejraselimovic This will break it

**Comment by elsalahy** [comment]
@nejraselimovic The contents of public folder need to overwrite the gh-pages contests.
In this PR you just merged a big public folder, so the change will not be deployed.

**Comment by elsalahy** [comment]
@nejraselimovic see this https://github.com/TheThingsIndustries/generic-node-docs/pull/49 as an example

**Pull request merged**
