### PR TITLE
doc: Make latest changes public second try

### PR DESCRIPTION
**Pull request by nejraselimovic**
#### Summary
Deploying latest docs changes, replaces reverted https://github.com/TheThingsIndustries/generic-node-docs/pull/55

@elsalahy how about now?

#### Checklist
- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by azerimaker — APPROVED** [review]

**Review by elsalahy — APPROVED** [review]
Looks good @nejraselimovic 🚀

**Comment by nejraselimovic** [comment]
> Looks good @nejraselimovic rocket

Thanks @elsalahy for all your help!

**Comment by elsalahy** [comment]
Anytime @nejraselimovic 
While this pull request seems ok, there seems  that you guys added a new UI element that breaks the build and the automated deployment, see  https://github.com/TheThingsIndustries/generic-node-docs/runs/8111637122?check_suite_focus=true

**Comment by elsalahy** [comment]
@nejraselimovic it seems to be the things inside doc folder bluma, did you update the theme internationally and was this file generated inside public folder?

**Comment by elsalahy** [comment]
This folder is new https://github.com/TheThingsIndustries/generic-node-docs/tree/gh-pages/doc

**Comment by nejraselimovic** [comment]
Oh damn it. No, this was not intentionally changed, and the `doc` folder was generated automatically.

**Pull request merged**
